version: '2'
services:
  db:
    image: mariadb:10.1
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mthai
      MYSQL_USER: mthai
      MYSQL_PASSWORD: datapw

  redis:
    image: redis:alpine

  nginx:
    image: nginx:alpine
    links:
      - fpm:fpm
    ports:
      - 80:80
    volumes:
      - "../site:/var/www/html"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"

  fpm:
    build: ./images/fpm
    links:
      - db:db
      - redis:redis
    volumes:
      - "../site:/var/www/html"
      - "./config/php.ini:/usr/local/etc/php/php.ini"

